### ISSUE TITLE
部分应用无效

### ISSUE THREAD

**Issue by Carpe0iem** [Xposed-Modules-Repo/io.github.tehcneko.satback#16]
部分应用顶部和底部栏仍黑白
京东 爱奇艺无效
![微信图片_20221204100535](https://user-images.githubusercontent.com/90304680/205470550-5ca7fa9c-98b9-49f3-8dac-63bb80521d9d.jpg)

**Comment by tehcneko** [comment]
内容本身是黑白的没办法解决
