### ISSUE TITLE
京东首页灰色

### ISSUE THREAD

**Issue by ForestL18** [Xposed-Modules-Repo/io.github.tehcneko.satback#2]
![Screenshot_2022-12-01-11-07-15-637_com jingdong app mall](https://user-images.githubusercontent.com/45709305/204956780-02805631-151c-4c54-a1b5-19fbde2cc183.png)

这个貌似改不了主题啥的

**Comment by tehcneko** [comment]
这个是服务端直接下发了黑白图片，没救
